### ISSUE TITLE
Does not recognize @-moz-document for CSS

### ISSUE THREAD

**Issue by Gitoffthelawn** [notepad-plus-plus/notepad-plus-plus#3858]
### Description of the Issue
Does not recognize **@-moz-document** for CSS

### Steps to Reproduce the Issue
Include:
`@-moz-document domain("example.com") {  CSS code }`
within your **.css** file.

### Expected Behavior
Proper syntax formatting.

### Actual Behavior
**@-moz-document** is not recognized, causing everything within its scope to have improper syntax formatting.

### Debug Information
Notepad++ v7.4.2

**Comment by Gitoffthelawn** [comment]
Bug still present 2+ years later in Notepad++ v7.8.2.  :(

Any chance of a fix?

BTW, I tried adding `-moz-document` and `@-moz-document` to the CSS section of `langs.xml`, but it did not make it work.

**Comment by ArkadiuszMichalski** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@document << not standard rule, only Firefox support.

**Comment by Gitoffthelawn** [comment]
It is not deprecated in userContent.css and userChrome.css, where it is required in many coding situations.  It's hard to estimate the number of people affected, but it's likely at least in the tens of thousands, possibly hundreds of thousands, or even millions.

Is there any real harm in adding it?  Will it require editing or adding more than 1 or 2 lines of code?

**Comment by ArkadiuszMichalski** [comment]
@Gitoffthelawn
This is a problem with Scintilla, not Notepad++. You can report this bug to Scintilla (for `LexCSS.cxx`): https://sourceforge.net/p/scintilla/bugs/
Basically `@-moz-document` and `@document` are recognized, but not it's contents. It should be trade simillar to `@media` or `@font-face` rules.

Code for test:
```css
@-moz-document domain("example.com") { 
  .column {
    width: 100%;
  }
}

@document url("https://www.example.com/") {
  .column {
    width: 100%;
  }
}

@media screen and (max-width: 600px) {
  .column {
    width: 100%;
  }
}

@font-face {
  font-family: MyHelvetica;
  src: local("Helvetica Neue Bold"),
       local("HelveticaNeue-Bold"),
       url(MgOpenModernaBold.ttf);
  font-weight: bold;
}
```

Result:
![image](https://user-images.githubusercontent.com/2730894/97165600-4246f300-1784-11eb-8248-49a3aaf6edb0.png)
