### ISSUE TITLE
Provide URL to download latest copy of Notepad++

### ISSUE THREAD

**Issue by vsimonian** [notepad-plus-plus/notepad-plus-plus#604]
Perhaps there may already be such a link, but is there a URL for the current version of Notepad++?

The URL I am familiar with is of the form

```
https://notepad-plus-plus.org/repository/6.x/6.8/
```

What would be nice is to have

```
https://notepad-plus-plus.org/repository/6.x/latest/
```

and

```
https://notepad-plus-plus.org/repository/latest/latest/
```

which would be incredibly helpful for writing batch scripts which fetch the latest version of Notepad++.

**Comment by Rikk** [comment]
I think @donho uses https://notepad-plus-plus.org/update/getDownloadUrl.php for [auto-update](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/bin/updater/gup.xml).

**Comment by vsimonian** [comment]
Thanks for the link, @Rikk! :+1: I had no idea.

However, I agree a "latest" URL would be nicer. Especially for use in simple scripts without having to parse XML.

**Comment by bcharboneauiherb** [comment]
Latest URL would be awesome, especially for Automation Practices such as chocolatey, Ansible and Powershell DSC.

**Comment by dansmith65** [comment]
The latest changes to the website broke the https://notepad-plus-plus.org/update/getDownloadUrl.php page mentioned above. I wrote a scraper script to extract the 64-bit download url from the website, download it, then silently run the installer: https://gist.github.com/dansmith65/a862f301fce553b26db9689ad0f87b6a

**Comment by markuman** [comment]
```yml
    - name: Fetch GitHub latest release information
      ansible.builtin.win_uri:
        url: "https://api.github.com/repos/notepad-plus-plus/notepad-plus-plus/releases/latest"
        return_content: true
        headers:
          Accept: "application/vnd.github.v3+json"
      register: github_response

    - name: Display latest release tag
      debug:
        var: github_response.json.tag_name | split('v') | last

    - name: Download np++
      ansible.windows.win_get_url:
        url: "https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/{{ github_response.json.tag_name }}/npp.{{ github_response.json.tag_name | split('v') | last }}.Installer.x64.exe"
        dest: "C:\\np.exe"
```
