### ISSUE TITLE
Syntax highlighting and content suggestion for CSS should support Flexible Box Layout

### ISSUE THREAD

**Issue by DavidFichtmueller** [notepad-plus-plus/notepad-plus-plus#711]
The [CSS Flex Box specification](http://www.w3.org/TR/css-flexbox-1/) is almost mature now, so Notepad++ should start supporting it for syntax highlighting and content suggestion. 
This code snippet:
```css
div.flex{
	/*syntax highlighting works*/
	font-size: 1.2em;
	color: #c0ffee;
	
	/*syntax highlighting doesn't work*/
	align-items: flex-start;
	flex-grow: 1;
	flex-shrink: 0;
	justify-content:flext-start;
	order: 2;
}
```
looks in Notepad 6.8.1 (most recent version) like this:
![css_flex_in_notepad_plus_plus](https://cloud.githubusercontent.com/assets/7805030/9244915/0dcaa1c2-41a0-11e5-9828-2b1ecd3fdddb.png)

This are of course not all of the flex-properties that are not properly highlighted. The properties to be added to the code should be taken from the specification and not from this ticket.
