### ISSUE TITLE
A fan Stylus theme for Notepad ++ website

### ISSUE THREAD

**Issue by the-j0k3r** [notepad-plus-plus/notepad-plus-plus#7621]
So the website is white per default, it has a nice toggle to switch to dark mode, that is until you refresh page or come back for a visit ALl white again. I know you gonna think later this post was a waste but I dont think so :smile: .

Also the dark mode mangles the icon color, OCD right? Its rhetorical Q so meh. ;)

![Screenshot_2019-11-19 Resources Notepad++](https://user-images.githubusercontent.com/31389848/69167228-e3e5af00-0af4-11ea-8caa-f948993cf387.png)

So heres what I did to fix it. I created my override theme for the site, my own dark/light themes switcher that stays dark always when I visit site and has the potential to style with custom colors, so everyone can configure the style.

If you want to use this style, install [Stylus](https://add0n.com/stylus.html) for either [Firefox](https://addons.mozilla.org/en-US/firefox/addon/styl-us/), [Chrome](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) or [Opera](https://addons.opera.com/en-gb/extensions/details/stylus/)

Then add the style below and save.

```css
/* ==UserStyle==
@name        Notepad++ Fan Dark 
@namespace   Style-it-themes
@version     1.0.0
@description A switchable theme light/dark selector for Stylus browser extension without mangling the logo too much =)
@homepageURL  https://github.com/style-it-themes
@author      Style-it-themes by: the-j0k3r
@license     MIT

@preprocessor stylus

@var checkbox switch-themes "Enable light mode" 0
@var checkbox switch-switch "Show site theme switcher" 0

==/UserStyle== */
@-moz-document regexp("^https://notepad-plus-plus\.org.*$") {
	if (!(switch-switch)) {
		footer label {
			display none;
		}
	} else {
		footer label {
			display inherit;
		}
	}
	:focus:not([tabindex="-1"]), [data-expands]:focus svg, 
	.patterns a:focus .text, [for="themer"] :focus + [aria-hidden] {
		outline: 4px solid transparent;
	}
	/* Added shake that spice */
	@keyframes shake-it {
		from {
			transform: scale3d(1, 1, 1);
		}
		10%, 20% {
			transform: scale3d(.9, .9, .9) rotate3d(0, 0, 1, -3deg);
		}
		30%, 50%, 70%, 90% {
			transform: scale3d(1.1, 1.1, 1.1) rotate3d(0, 0, 1, 3deg);
		}
		40%, 60%,	80% {
			transform: scale3d(1.1, 1.1, 1.1) rotate3d(0, 0, 1, -3deg);
		}
		to {
			transform: scale3d(1.1, 1.1, 1.1) rotate3d(0, 0, 1, 4deg)
		}
	}
	img[src$="logo.svg"]:hover {
		animation-name: shake-it;
		animation-duration: 1s;
	}
	if (!(switch-themes)) {
		body,	rss {
			background: #111;
			color: #bbb;
		}
		[href="#main"] {
			border-bottom: 2px solid #555;
		}
		img[src$="logo.svg"] {
			background: none;
			filter: invert(1) hue-rotate(180deg) brightness(180%) contrast(60%);
		}
		.pattern a[aria-current][href] {
			background-color: #ccc;
			color: #111 !important;
		}
		.pattern a[href]:not([aria-current]):hover {
			color: #eee;
		}
		strong, h1,	h2,	h3,	h4,	h5 {
			color: #eee;
		}
		p, .text {
			color: inherit
		}
		header.intro-and-nav,
		.patterns-list li + li {
			border-color: #555;
		}
	}
	else {
		[href="#main"] {
			border-bottom: 3px solid #111;
		}
		body, [href="#main"],	rss {
			background: #eee;
			color: #111;
		}
		.pattern a[aria-current][href] {
			background-color: #111;
			color: #eee !important;
		}
		.pattern a[href]:not([aria-current="Page"]):hover {
			color: #666;
		}
		.pattern a[href]:hover {
			color: #111;
		}
		strong, h1, h2, h3, h4, h5 {
			color: #111;
		}
		p, .text {
			color: inherit;
		}
	}
}
```
This is how the site looks with it

![generic](https://user-images.githubusercontent.com/31389848/69171546-79d10800-0afc-11ea-8392-ca96327e8970.gif)

Feel free to use the CSS for the actual site, the logo remains more or less unmangled and its dark or light when I want. Its MIT lic.

Enjoy or not. Keep smiling...

>May update it later to add other themes other than light/dark and make it auto-updatable depends on interest.
