### ISSUE TITLE
YAML doesn't use NUMBER for inline lists

### ISSUE THREAD

**Issue by eslindsey** [notepad-plus-plus/notepad-plus-plus#8792]
### Description of the Issue
In a YAML file, NUMBERs should be highlighted using the NUMBER format. But in inline lists they are not.

### Steps to Reproduce the Issue
1. Enter the following valid YAML in a file:
```yaml
1091871393: # Verified 9/1/20
    name: Pune,
    level: 16,
    hostiles:
        - [Pakled Thief, 15, B, 6548]
        - [Pakled Thief, 16, B, 9457]
        - [Pakled Thief, 17, B, 11354]
```

### Expected Behavior
The "15" next to "Pakled Thief" should be highlighted the same as the "16" next to "level".

### Actual Behavior
Everything after the dash is styled the same.

### Debug Information
Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 8.1 (64-bit) 
OS Build : 9600.0
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

![Screenshot](https://i.imgur.com/L01azaM.png)
